version: '3'

services: 
    api:
        image: youtube_downloader:api
        build:
            context: "./API/"
        volumes:
            - ./Media:/app/media/
            - ./Cache:/app/cache/
        ports:
            - "10080:8000"
        env_file:
            - "api.env"
    # front_end:
    #     image: youtube_downloader:front_end
    #     build:
    #         context: "./FrontEnd/"
    #     volumes:
    #         - ./Media:/var/lib/youtube_downloader
    #         - ./FrontEnd:/home/node/app
    #     ports:
    #         - "8100:3000"